"""Emit the connection-failure evidence, as a document an opponent can check.

    uv run python scripts/evidence.py --out matches/evidence-uoh-sqak.md

Written because uoh-sqak asked for evidence and do not accept that the failures
are theirs. That is a reasonable position: our previous answer was "it was DNS"
and it was wrong, published from one log line out of 154.

The tone here is deliberate. It reports what the log contains, names the control
that makes the comparison meaningful, and stops at a hypothesis — because a
hypothesis is what the data supports. An opponent who has been precise and
honest with us all week is owed the same.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from najamjad_agent.analysis.connection_forensics import (  # noqa: E402
    endpoint_health,
    first_faults,
    load_events,
    unnamed_share,
)

PREAMBLE = """# Connection failures — what our log actually contains

Generated by `scripts/evidence.py` from our own `workspace/events.jsonl`. Every
number below is reproducible from that file; the script is in the repository.

**Correcting ourselves first.** We previously told you this was DNS. That was
wrong, and it was based on one log line. `[Errno -3] Temporary failure in name
resolution` appears in **1 of {total} failures**. Our DNS pre-warm (`dns.warmed`)
is present in the log and *succeeded* on your hostname, so resolution is
exonerated by our own record, not just by argument.
"""

CONTROL = """
## The control

Identical client code, identical process, identical session lifecycle, dialling
several endpoints in the same period. **The client is the constant; the endpoint
is the variable.**

| endpoint | opened | failed | failure rate |
|---|---:|---:|---:|
{rows}

We are not claiming this proves a cause. We are claiming it is the reason we
cannot locate the fault on our side: the same code succeeds elsewhere and fails
here, and one tunnel provider is *not* uniformly better than another in this
table — which is why we are asking to diagnose it jointly rather than asserting
it is yours.
"""

MECHANISM = """
## What opened each failure cascade

A storm logs one real fault and then many copies of the wrapper our retry loop
produces, so counting every failure equally measures our retry policy rather
than the fault. These are the *first* failures only:

{faults}

`{unnamed} of {total}` failures carried **no usable message at all** — the
wrapper stringifies to `Client failed to connect: ` with nothing after the
colon. That is why this took a week: the log recorded the failure's type 152
times and its cause zero times. We have fixed our instrumentation
(`shared/error_detail.py`) so the next match records the underlying exception
and its cause chain.

## What we think, stated as a hypothesis

An empty-message `ConnectError` together with `Server disconnected without
sending a response`, against a peer whose own access log shows requests served
with zero 4xx/5xx, is consistent with the connection being refused or reset
**before it reaches your application** — which would be invisible in both of our
access logs, which is exactly what we both observe.

We are **not** asserting this. We would like to test it.

## What we propose

1. The two-game diagnostic you offered, with synchronised timestamps. Every one
   of our events now carries a UTC `ts`; previously none did, which is why your
   offer could not be taken up before.
2. If you can, run one series over a different tunnel. If the stalls vanish, we
   have our answer; if they follow you, the fault is ours and we will own it.
3. Our side is already instrumented for (1) and (2) and we will publish whatever
   it shows, including if it shows the fault is ours.
"""


def render(events_path: Path) -> str:
    """Build the report from a log file."""
    events = load_events(events_path)
    unnamed, total = unnamed_share(events)
    rows = "\n".join(
        f"| `{each.url}` | {each.opened} | {each.failed} | {each.failure_rate:.0%} |"
        for each in endpoint_health(events)
        if each.attempts
    )
    faults = "\n".join(f"- `{label}` — {count}x" for label, count in first_faults(events).most_common(8))
    return (
        PREAMBLE.format(total=total)
        + CONTROL.format(rows=rows)
        + MECHANISM.format(unnamed=unnamed, total=total, faults=faults or "- none recorded")
    )


def main() -> int:
    """Render the evidence document to stdout or a file."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--events", type=Path, default=ROOT / "workspace" / "events.jsonl")
    parser.add_argument("--out", type=Path, default=None)
    args = parser.parse_args()
    if not args.events.exists():
        print(f"no event log at {args.events}", file=sys.stderr)
        return 1
    report = render(args.events)
    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(report, encoding="utf-8")
        print(f"wrote {args.out}")
    else:
        print(report)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
